framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                  - doctrine_transaction
            event.bus:
                # the 'allow_no_handlers' middleware allows to have no handler
                # configured for this bus without throwing an exception
                default_middleware: allow_no_handlers
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\RentCar\Domain\Model\Car\CarWasCreated: async
