# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    
    App\RentCar\Application\Car\CreateCarCommandHandler:
        tags: [ messenger.message_handler ]
    App\RentCar\Application\Reservation\CancelReservationCommandHandler:
        tags: [ messenger.message_handler ]
    App\RentCar\Application\Reservation\CreateReservationCommandHandler:
        tags: [ messenger.message_handler ]
    App\RentCar\Application\Customer\CreateCustomerCommandHandler:
        tags: [ messenger.message_handler ]
    App\RentCar\Application\Match\CreateCarMatchCommandHandler:
        tags: [ messenger.message_handler ]        

    # another service is subscribing to this domain events

    App\RentCar\Application\External\CustomerWasCreatedHandler:
      tags:
        - name: messenger.message_handler          
          handles: App\RentCar\Domain\Model\Customer\CustomerWasCreated

    App\RentCar\Application\External\CarWasCreatedHandler:
      tags:
        - name: messenger.message_handler
          handles: App\RentCar\Domain\Model\Car\CarWasCreated
